cfrg/draft-irtf-cfrg-aead-limits

draft-wood-cfrg-aead-limits.md

Fix AES-GCM bound typo (7 != 9).

---

draft-irtf-cfrg-aead-limits.md

I did some analysis of Theorem 3.1 in the GCM MU paper.
The difference is small.  Theorem 3.1 adds `σ/2^128` to the advantage.
Theorem 4.3 adds `1/2^48` to the advantage.
The difference is felt when `σ` gets large, then nonce randomization
gets better.  It's not as small a value as I had expected (2^80 is a
LARGE number) based on the original Bellare/Tackmann work, but it's
there.
I restored the constant factor from the second term to the equations.  
I tried a few things, but forcing a minimum on B seemed like it would be safest.
This is for yaronf/I-D#203.

No nonce randomization

---

draft-irtf-cfrg-aead-limits.md

I reviewed the formulae and I believe that we are safe in recommending
l=1 for byte counting.  It's definitely inefficient, but the
inefficiency doesn't translate into a security issue as we have always
assumed that l is variable.
Closes #35.

Advice on applying limits

---

draft-irtf-cfrg-aead-limits.md

We didn't really say anything about rekeying, which is the most obvious
way of managing limits.
This was raised (indirectly) by @emanjon (via #37) and also @smyshsv in #10.
I considered doing more for #10 here, but I think that it is probably
best to leave the RFC 8645 AEAD definitions (those with internal
rekeying) out of this.  We've very deliberately concentrated on modes
that have widespread deployment and -- cool as they are -- I am not
aware of any implementation of internal rekeying modes.  (FWIW, it looks
like the analysis there is entirely consistent with the multi-key
setting results we have.)
Closes #10.

Editorial pass

---

draft-irtf-cfrg-aead-limits.md

TLS 1.2 uses random, partially implicit nonces. The applicable multi-user analysis for this is in the GCM MU paper, Theorem 5.3.
The major difference to the TLS 1.3 / nonce randomization setting is that
1. the nonce collision term `2^-48` is replaced by a negligible term (`2^-7t = 2^-224`)
2. the `d` term becomes much larger, yielding a quadratic component (`(q+v)*o` resp. `(q+v)^2`) over `2^k`
(This revises #33.)

Partially implicit nonces

---

draft-irtf-cfrg-aead-limits.md

As Joe notes, we assume a fixed length.  The definitions in the IETF all
use N_MIN = N_MAX = 12, but the NIST publications often veer into all
sorts of wild fantasies of arbitrary nonce length.  This rarely works
well, as we see from the analysis in 2018/993.
Closes #41.

Nonce length is fixed

---

draft-irtf-cfrg-aead-limits.md

Added multi-key bounds from https://doi.org/10.1145/3460120.3484814  (CCS 2021).
- ChaCha20Poly1305 has multi-key AE and integrity limit identical to single-user case (just that `v` is counted across all keys), multi-key confdentiality limit is bounded at very low levels
- multi-key GCM bound improved: the above work shows that the constant additive 2^-48 term can be waived without further side-effects on the dominant terms
- added multi-key examples (table)

ChaCha20Poly1305 multi-key bounds

---

draft-irtf-cfrg-aead-limits.md

The extra term really isn't relevant here unless you have enormous messages.  By which I mean, messages that are 32 Yottabytes in size.  That's a single encryption of that size.  2^100 of those messages, with every one of them that big.  No rekeying either.
It's even less plausible for smaller q.  A q of 1 results in a message size of 2^139 bytes.
Neither is concretely possible as RFC 7539 has just a 32-bit counter, which limits messages to 256GB.

Simplify CA for ChaCha

---

draft-irtf-cfrg-aead-limits.md

These are more readable in HTML this way.

Use superscripts for multi-key example

---

draft-irtf-cfrg-aead-limits.md

We take a lot of liberties throughout, which are generally well signposted, but I thought it might be helpful to include something more general in the lead-in.  This also addresses the non-repeating nonce comment.

Add a section on assumptions and approximations

---

draft-irtf-cfrg-aead-limits.md

This was pretty hard to automate as you might imagine, but I agree with Scott about the l being easily confused (did I type 1 or l or I?  ¯\\(°\_o)/¯).
I also tried to be more consistent in the application of backticks throughout.  There are a few changes that relate to that.  I've also tried to remove a few places where dropping a variable name into prose might be jarring.

Convert all instances of l to L

---

draft-irtf-cfrg-aead-limits.md

Following up on Scott Fluhrer's CFRG review (Feb 14, 2023), I've added explanations for two bounds:
1. **GCM integrity**: We're using an improved bound (as in {{AEBounds}}) from {{GCMProofs}, Equation (22), where the second term mentioned in #55 vanishes by applying a result from Bernstein on random permutations.
2. **CCM confidentiality**: The `2L` here comes from the way message blocks are counted twice for the terms `l_E` (or `l_F`) in {{!CCM-ANALYSIS=DOI.10.1007/3-540-36492-7_7}}, not from counting `l_E + l_F` (that's integrity, and hence `2L * (q + v)` there).
I.e., in both cases the bounds as stated are correct, but I thought that added explanation would be helpful.

Explain GCM IA and CCM CA bounds

---

draft-irtf-cfrg-aead-limits.md

Number of forgery attempts should include the "ongoing one" for which we provide a bound. I.e., if the attacker made `x` (failed) attempts already, then the bounds are for `v = x + 1` attempts / decryption queries overall.
This is in response to John Mattsson's comment:
> In their paper “Breaking and Repairing GCM Security Proofs”, Iwata, Ohashi, and Minematsu define the variable q′ to be decryption queries. The draft instead uses v to mean failed AEAD decryption invocations. The idea to replace “decryption queries” with “failed AEAD decryption invocations” is very good but causes some problems.
> 
> IA <= 2 * (v * (L + 1)) / 2^128
> v - Number of attacker forgery attempts (failed AEAD decryption invocations)            
> 
> When using the formulas in the paper, it’s clear that q’ is 1 …

Number of forgery attempts

---

draft-irtf-cfrg-aead-limits.md

Addressing comments by John Mattsson [on CFRG mailing (10 Nov 2023)](https://mailarchive.ietf.org/arch/msg/cfrg/rF_r7lWvPaeenvsSyBpY5H3oljg/) as follows:
- *major:* "I am strongly against any suggestion that the single-key confidentiality and integrity advantages should be used to calculate rekeying limits [...]"
- emphasized that multi-key limits should be used when rekeying, noted that offline work is about time not memory
- *minor:* "I think it would be good if bounds for OCB could be included."
- (no change)
- *minor:* "I think this needs to be expanded to explain that there might be a huge number of keys shared between two parties."
- added note on multiple sessions between parties and many keys within sessions in introduction
- *minor:* "Would be good if this also mentioned key …

addressing comments by John Mattsson (10 Nov 2023)

---

draft-irtf-cfrg-aead-limits.md

[AEBounds] is on ePrint now – fixes #65

Fix AEBounds link

---

draft-irtf-cfrg-aead-limits.md

The original result in {{ChaCha20Poly1305-SU}} was actually flawed, and corrected in our {{ChaCha20Poly1305-MU}} work (retaining the same bound).  Kenny pointed out that readers should hence not take {{ChaCha20Poly1305-SU}} as the reference.
Reworded to reflect this.

ChaChaPoly SU result wording

---

draft-irtf-cfrg-aead-limits.md

I spent far too much time trying to find independent ways to reproduce djb's cost estimates, but was unable to make a significant dent in that. Still, that's not the central point here, so I'm keeping them.
To give an example, c8g.metal-24xl instances have a spot price of less than USD1 per hour (https://instances.vantage.sh/aws/ec2/c8g.metal-24xl). If we assume that those are capable of performance roughly on par with my own machine, but with 6 times the parallel capacity, then they should be easily capable of 3 billion blocks per second or 2^43 blocks per hour. Spending USD1MM would therefore mean 2^63 blocks, which is a long way short of the above estimate.

Add a note about offline work

---

draft-irtf-cfrg-aead-limits.md

Reworded intro paragraph on rekeying to avoid confusion and emphasize that multi-key bounds SHOULD be used when rekeying.
@martinthomson : Is "SHOULD" the right key word here?

Rekeying reworded

---

draft-irtf-cfrg-aead-limits.md

Added details on PRP advantage being used for AES and PRF advantage being used for ChaCha20, to accompany the #70 Offline Work discussion.

Proof comments

---

draft-irtf-cfrg-aead-limits.md

We use CA and IA as steps toward placing a bound on AEA; we shouldn't emphasize the use of these things separately.
As Thomas notes, your AEAD doesn't work well if you lose integrity (there are modes that can do that catastrophically, even). More importantly, IND-CPA isn't much chop against an attacker that can apply arbitrary forgeries because integrity is busted. But this is an AEAD, with both parts active.  As long as both pieces are functional, we retain confidentiality.
This attempts to make a few targeted changes to properly emphasize that point.

AE limits are what matter most
